language: php
sudo: false
services:
  - docker

env:
  - PHP_VERSION=5.4 ENABLE_MCRYPT=0
  - PHP_VERSION=5.4 ENABLE_MCRYPT=1
  - PHP_VERSION=5.5 ENABLE_MCRYPT=0
  - PHP_VERSION=5.5 ENABLE_MCRYPT=1
  - PHP_VERSION=5.6 ENABLE_MCRYPT=0
  - PHP_VERSION=5.6 ENABLE_MCRYPT=1
  - PHP_VERSION=7.0 ENABLE_MCRYPT=0
  - PHP_VERSION=7.0 ENABLE_MCRYPT=1

matrix:
  allow_failures:
    - env: PHP_VERSION=5.4 ENABLE_MCRYPT=0
    - env: PHP_VERSION=5.5 ENABLE_MCRYPT=0
    - env: PHP_VERSION=5.6 ENABLE_MCRYPT=0
    - env: PHP_VERSION=7.0 ENABLE_MCRYPT=0
  fast_finish: true

install:
  - curl -sS https://getcomposer.org/installer | php
  - travis_retry php composer.phar install

script:
  - ./util.sh run-test
