language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
env:
  - USE_RUNKIT=0
  - USE_RUNKIT=1

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

before_script:
  - gcc -v
  - pushd /tmp
  - git clone https://github.com/tototoshi/runkit.git
  - pushd runkit
  - if php -v | head -1 | grep '^PHP 5.6' > /dev/null; then git checkout -t -b php5.6 origin/php5.6; fi
  - pecl install package.xml
  - popd
  - popd
  - echo 'runkit.internal_override = "1"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/my_runkit.ini
  
install:
  - travis_retry composer install
  - pecl install channel://pecl.php.net/runkit-0.9

script:
  - vendor/bin/phpunit